name: bottom_nav_layout
description: A quick and powerful app layout. Supports page state preservation, lazy page loading, and has a page backstack.
version: 3.0.9
homepage: https://github.com/m-azyoksul/bottom_nav_layout

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  universal_io: ^2.0.4

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
